# Project information

site_name: HYBSW
site_description: HYBSW Applications Documentation
site_author: Hynek Broulik
plugins: []
 
nav:
    - Home: index.md
    - AgilityE02: agilitye02.md
    - AgilityA03: agilitya03.md
    - MedsListLite: medslistlite.md
    - LiPoCalc: lipocalc.md
    
        